### ISSUE TITLE
How to use it in Linux?

### ISSUE THREAD

**Issue by kytas** [vnau/KeePass2Trezor#7] opened 2023-12-26 20:39 UTC
Hello,
i wanna try this plugin on linux ubuntu 22.04, but i have same behavior like your close issue.
How to use it in Linux? #2 
I tried compiled from source, but nothing helped ? Do u have any ideas, whats wrong ? 
Thanks

**Comment by vnau** [comment] 2023-12-27 02:12
Hi Kytas,

prerequisites for the plugin in Linux is installing the libusb-1.0.0 library and [the udev rule](https://trezor.io/learn/a/udev-rules) for Trezor devices.
This can be done with the two corresponding commands:
```
sudo apt-get install libusb-1.0-0
sudo curl https://data.trezor.io/udev/51-trezor.rules -o /etc/udev/rules.d/51-trezor.rules
```
I believe the problem is in one of these steps, because the plugin simply does not see the device.

**Comment by vnau** [comment] 2023-12-27 02:17
Hi Kytas,

prerequisites for the plugin in Linux is installing the libusb-1.0.0 library and [the udev rule](https://trezor.io/learn/a/udev-rules) for Trezor devices.
This can be done with the two corresponding commands:
```
sudo apt-get install libusb-1.0-0
sudo curl https://data.trezor.io/udev/51-trezor.rules -o /etc/udev/rules.d/51-trezor.rules
```
I believe the problem is in one of these steps, because the plugin simply does not see the device.

**Comment by kytas** [comment] 2023-12-27 06:26
Hello, 
i have the newest version of libusb. 
libusb-1.0-0 is already the newest version (2:1.0.25-1ubuntu2).
and udev rules too. 
I am using trezor for loging into PC etc. And it works perfect. 

I have trezor 3, do u think, that this may cause the problem ?

**Comment by vnau** [comment] 2023-12-27 11:05
> I have trezor 3, do u think, that this may cause the problem ?

Oh, this could definitely be an issue as the plugin hasn't been tested with Safe 3.

I took a quick look at the Trezor code and found that they haven't changed the product and vendor ID for the new model. Udev rules have not changed since the Model T as well. So there's a chance this might work without code modifications.

Have you tried the Keepass2Trezor with Safe 3 on Windows, does it really work?

**Comment by kytas** [comment] 2023-12-27 11:27
I tried now on virtual windows 10 and its works. 
Do u have any idea? 
If i return to work i could test trezor one, if its working.

**Comment by vnau** [comment] 2023-12-27 14:28
Thanks for checking out Safe 3 on Windows, glad to know it functioning.

Just tried using Keepass2Trezor v1.0.1 from artifacts (built with AppVeyor, VS2015), it works fine with Trezor One on Ubuntu 23.10 on VirtualBox.

The only problem was in loading the plugin due to the dependency on netstandard 2.0, but in this case, unlike #2, the "Connect your Trezor device" window doesn't even show up. Installing **mono-complete** solved it.

If the device running on Windows and the "Connect your Trezor device" window appears on Linux, I'd still assume there's something wrong with the link layer - usblib or udev, but it's hard to guess what exact.

**Comment by kytas** [comment] 2023-12-27 15:54
I found the problem. 
After i installed libusb-1.0-0-dev trezor get work fine.

**Comment by vnau** [comment] 2023-12-27 16:54
Great! Thanks for sharing the solution.
I'm closing the issue as resolved.

**Closed by vnau** 2023-12-27 16:54 UTC
